# Generated by Django 3.1.4 on 2020-12-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('S', 'Science'), ('E', 'Engineering'), ('T', 'Technology')], default='T', max_length=20),
        ),
    ]
